#ifndef MONITORIA_CONFIG_H
#define MONITORIA_CONFIG_H

#define MONITORIA_MFRC522_SS 10
#define MONITORIA_MFRC522_RST 9

#define MONITORIA_SIM800L_BAUD_RATE 4600
#define MONITORIA_SIM800L_TX 0
#define MONITORIA_SIM800L_RX 1

#define MONITORIA_SMS_MESSAGE "Attendance recorded."

#endif