#ifndef MONITORIA_CONFIG_H
#define MONITORIA_CONFIG_H

#define MONITORIA_MFRC522_SS D4
#define MONITORIA_MFRC522_RST D3

#define MONITORIA_SIM800L_BAUD_RATE 4600
#define MONITORIA_SIM800L_TX D10
#define MONITORIA_SIM800L_RX D9

#define MONITORIA_SERVER_SSID "Monitoria"
#define MONITORIA_SERVER_PASSWORD "!tUblxofr6k+fretr&h5"

#define MONITORIA_SERVER_PORT 80
#define MONITORIA_SERVER_LOCAL_IP 192, 168, 1, 1
#define MONITORIA_SERVER_SUBNET 255, 255, 255, 0
#define MONITORIA_SERVER_GATEWAY MONITORIA_SERVER_LOCAL_IP

#define MONITORIA_LCD_I2C_ADDRESS 0x27
#define MONITORIA_LCD_I2C_COLS 16
#define MONITORIA_LCD_I2C_ROWS 2

#define MONITORIA_LED_SUCCESS D8
#define MONITORIA_LED_FAIL D0

#define MONITORIA_SMS_MESSAGE "Attendance recorded."

#endif