#ifndef MONITORIA_CONFIG_H
#define MONITORIA_CONFIG_H

#define MONITORIA_MFRC522_SS D4
#define MONITORIA_MFRC522_RST D3

#define MONITORIA_SIM800L_BAUD_RATE 4600
#define MONITORIA_SIM800L_TX 0
#define MONITORIA_SIM800L_RX 1

#define MONITORIA_SERVER_SSID "Monitoria"
#define MONITORIA_SERVER_PASSWORD "!tUblxofr6k+fretr&h5"

#define MONITORIA_SERVER_PORT 80
#define MONITORIA_SERVER_LOCAL_IP 192, 168, 1, 1
#define MONITORIA_SERVER_SUBNET 255, 255, 255, 0
#define MONITORIA_SERVER_GATEWAY MONITORIA_SERVER_LOCAL_IP

#define MONITORIA_SMS_MESSAGE "Attendance recorded."

#endif